project:
  type: website

website:
  title: "microGalaxy paper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - explore-publications.qmd
      - survey.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

